version: '3.6'

services:
  mysql:
    image: mysql
    container_name: mysql_c
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_admin
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql:/data

  adminer:
    image: adminer
    container_name: adminer_c
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo
    container_name: mongo_c
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
      MONGO_INITDB_DATABASE: rest_main
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo:/data

  mongo-express:
    image: mongo-express
    container_name: mongo_express_c
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: user
      ME_CONFIG_MONGODB_URL: mongodb://user:user@mongo:27017/

  # admin:
  #   build: ./admin
  #   container_name: admin_c
  #   ports:
  #     - 8000:8000
  #   stdin_open: true
  #   volumes:
  #     - ./admin:/app/node_modules
  #     - ./admin:/app
  #   tty: true
